name: classyshark
summary: a standalone binary inspection tool.
description: a standalone binary inspection tool for Android developers.
  
adopt-info: devmode # use 'strict' once you have the right plugs and slots

grade: stable
confinement: devmode

architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

apps:
  classyshark:
    command: bin/android-classyshark
    plugs:
      - home
      - network

parts:
  classyshark:
    plugin: 
    source: https://github.com/google/android-classyshark.git
    source-type: git
    override-pull: |
       git clone https://github.com/google/android-classyshark.git src/github.com/google/android-classyshark
       cd src/github.com/google/android-classyshark
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/v//')"
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$(git describe --tags | sed 's/v//')"
      override-build: |
      export GOPATH=$PWD
      cd src/github.com/google/android-classyshark
      env CGO_ENABLED=0 GOOS=linux \
      go build --ldflags "-s -w \
        -X 'github.com/google/android-classyshark/version.GitCommit=$(git rev-list -1 HEAD)' \
        -X 'github.com/google/android-classyshark/version.Version=$(git describe --tags --abbrev=0)'" \
        -a -installsuffix cgo -o $SNAPCRAFT_PART_INSTALL/bin/android-classyshark
    build-snaps:
      - java
    build-packages:
      - git
      - sed
